// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.turbotransfer_core

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_turbotransfer_core_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_turbotransfer_core_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "turbotransfer_core"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}


























































































// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            loadIndirect<UniffiLib>(componentName = "turbotransfer_core")
            .also { lib: UniffiLib ->
                uniffiCheckContractApiVersion(lib)
                uniffiCheckApiChecksums(lib)
                }
        }
        
    }

    fun uniffi_turbotransfer_core_fn_func_cancel_transfer(`transferId`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_turbotransfer_core_fn_func_enter_receive_mode(`address`: RustBuffer.ByValue,`destDir`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_turbotransfer_core_fn_func_export_transfer_logs(`transferId`: RustBuffer.ByValue,`outputDir`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_turbotransfer_core_fn_func_get_devices(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_turbotransfer_core_fn_func_get_progress(`transferId`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_turbotransfer_core_fn_func_get_transfer_bottleneck_report(`transferId`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_turbotransfer_core_fn_func_get_transfer_log_json(`transferId`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_turbotransfer_core_fn_func_get_transfer_logs(`transferId`: RustBuffer.ByValue,`maxEvents`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_turbotransfer_core_fn_func_get_transfers(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_turbotransfer_core_fn_func_init_logger(uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_turbotransfer_core_fn_func_list_transfer_logs(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_turbotransfer_core_fn_func_pause_transfer(`transferId`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_turbotransfer_core_fn_func_resume_transfer(`transferId`: RustBuffer.ByValue,`transportPref`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_turbotransfer_core_fn_func_set_data_directory(`path`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_turbotransfer_core_fn_func_start_transfer(`filePath`: RustBuffer.ByValue,`fileName`: RustBuffer.ByValue,`deviceId`: RustBuffer.ByValue,`transportPref`: RustBuffer.ByValue,`address`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_turbotransfer_core_fn_func_stop_receive_mode(uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_turbotransfer_core_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_turbotransfer_core_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_turbotransfer_core_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun ffi_turbotransfer_core_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_turbotransfer_core_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_free_u8(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_turbotransfer_core_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_free_i8(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_turbotransfer_core_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_free_u16(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_turbotransfer_core_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_free_i16(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_turbotransfer_core_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_free_u32(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_turbotransfer_core_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_free_i32(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_turbotransfer_core_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_free_u64(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_turbotransfer_core_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_free_i64(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_turbotransfer_core_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_free_f32(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    fun ffi_turbotransfer_core_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_free_f64(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    fun ffi_turbotransfer_core_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_cancel_pointer(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_free_pointer(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun ffi_turbotransfer_core_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_turbotransfer_core_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_cancel_void(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_free_void(`handle`: Long,
    ): Unit
    fun ffi_turbotransfer_core_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_turbotransfer_core_checksum_func_cancel_transfer(
    ): Short
    fun uniffi_turbotransfer_core_checksum_func_enter_receive_mode(
    ): Short
    fun uniffi_turbotransfer_core_checksum_func_export_transfer_logs(
    ): Short
    fun uniffi_turbotransfer_core_checksum_func_get_devices(
    ): Short
    fun uniffi_turbotransfer_core_checksum_func_get_progress(
    ): Short
    fun uniffi_turbotransfer_core_checksum_func_get_transfer_bottleneck_report(
    ): Short
    fun uniffi_turbotransfer_core_checksum_func_get_transfer_log_json(
    ): Short
    fun uniffi_turbotransfer_core_checksum_func_get_transfer_logs(
    ): Short
    fun uniffi_turbotransfer_core_checksum_func_get_transfers(
    ): Short
    fun uniffi_turbotransfer_core_checksum_func_init_logger(
    ): Short
    fun uniffi_turbotransfer_core_checksum_func_list_transfer_logs(
    ): Short
    fun uniffi_turbotransfer_core_checksum_func_pause_transfer(
    ): Short
    fun uniffi_turbotransfer_core_checksum_func_resume_transfer(
    ): Short
    fun uniffi_turbotransfer_core_checksum_func_set_data_directory(
    ): Short
    fun uniffi_turbotransfer_core_checksum_func_start_transfer(
    ): Short
    fun uniffi_turbotransfer_core_checksum_func_stop_receive_mode(
    ): Short
    fun ffi_turbotransfer_core_uniffi_contract_version(
    ): Int
    
}

private fun uniffiCheckContractApiVersion(lib: UniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_turbotransfer_core_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}

@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: UniffiLib) {
    if (lib.uniffi_turbotransfer_core_checksum_func_cancel_transfer() != 37359.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_turbotransfer_core_checksum_func_enter_receive_mode() != 40189.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_turbotransfer_core_checksum_func_export_transfer_logs() != 40795.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_turbotransfer_core_checksum_func_get_devices() != 21628.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_turbotransfer_core_checksum_func_get_progress() != 59093.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_turbotransfer_core_checksum_func_get_transfer_bottleneck_report() != 7569.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_turbotransfer_core_checksum_func_get_transfer_log_json() != 14680.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_turbotransfer_core_checksum_func_get_transfer_logs() != 37922.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_turbotransfer_core_checksum_func_get_transfers() != 32457.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_turbotransfer_core_checksum_func_init_logger() != 46680.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_turbotransfer_core_checksum_func_list_transfer_logs() != 33245.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_turbotransfer_core_checksum_func_pause_transfer() != 57812.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_turbotransfer_core_checksum_func_resume_transfer() != 47857.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_turbotransfer_core_checksum_func_set_data_directory() != 5757.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_turbotransfer_core_checksum_func_start_transfer() != 54351.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_turbotransfer_core_checksum_func_stop_receive_mode() != 23398.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            args.filterIsInstance<Disposable>()
                .forEach(Disposable::destroy)
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer

/**
 * @suppress
 */
public object FfiConverterUShort: FfiConverter<UShort, Short> {
    override fun lift(value: Short): UShort {
        return value.toUShort()
    }

    override fun read(buf: ByteBuffer): UShort {
        return lift(buf.getShort())
    }

    override fun lower(value: UShort): Short {
        return value.toShort()
    }

    override fun allocationSize(value: UShort) = 2UL

    override fun write(value: UShort, buf: ByteBuffer) {
        buf.putShort(value.toShort())
    }
}

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterDouble: FfiConverter<Double, Double> {
    override fun lift(value: Double): Double {
        return value
    }

    override fun read(buf: ByteBuffer): Double {
        return buf.getDouble()
    }

    override fun lower(value: Double): Double {
        return value
    }

    override fun allocationSize(value: Double) = 8UL

    override fun write(value: Double, buf: ByteBuffer) {
        buf.putDouble(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}



data class FfiBottleneckReport (
    var `transferId`: kotlin.String, 
    var `fileName`: kotlin.String, 
    var `fileSize`: kotlin.ULong, 
    var `role`: kotlin.String, 
    var `totalDurationMs`: kotlin.ULong, 
    var `avgThroughputMbps`: kotlin.Double, 
    var `peakThroughputMbps`: kotlin.Double, 
    var `senderDiskReadMbps`: kotlin.Double, 
    var `senderDiskReadAvgUs`: kotlin.Double, 
    var `senderDiskReadP95Us`: kotlin.Double, 
    var `senderChecksumMbps`: kotlin.Double, 
    var `senderChecksumAvgUs`: kotlin.Double, 
    var `receiverDiskWriteMbps`: kotlin.Double, 
    var `receiverDiskWriteAvgUs`: kotlin.Double, 
    var `receiverDiskWriteP95Us`: kotlin.Double, 
    var `receiverMaxQueueDepth`: kotlin.UInt, 
    var `receiverFinalizeMs`: kotlin.ULong, 
    var `channels`: List<FfiChannelMetric>, 
    var `primaryBottleneck`: kotlin.String, 
    var `recommendations`: List<kotlin.String>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiBottleneckReport: FfiConverterRustBuffer<FfiBottleneckReport> {
    override fun read(buf: ByteBuffer): FfiBottleneckReport {
        return FfiBottleneckReport(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterSequenceTypeFfiChannelMetric.read(buf),
            FfiConverterString.read(buf),
            FfiConverterSequenceString.read(buf),
        )
    }

    override fun allocationSize(value: FfiBottleneckReport) = (
            FfiConverterString.allocationSize(value.`transferId`) +
            FfiConverterString.allocationSize(value.`fileName`) +
            FfiConverterULong.allocationSize(value.`fileSize`) +
            FfiConverterString.allocationSize(value.`role`) +
            FfiConverterULong.allocationSize(value.`totalDurationMs`) +
            FfiConverterDouble.allocationSize(value.`avgThroughputMbps`) +
            FfiConverterDouble.allocationSize(value.`peakThroughputMbps`) +
            FfiConverterDouble.allocationSize(value.`senderDiskReadMbps`) +
            FfiConverterDouble.allocationSize(value.`senderDiskReadAvgUs`) +
            FfiConverterDouble.allocationSize(value.`senderDiskReadP95Us`) +
            FfiConverterDouble.allocationSize(value.`senderChecksumMbps`) +
            FfiConverterDouble.allocationSize(value.`senderChecksumAvgUs`) +
            FfiConverterDouble.allocationSize(value.`receiverDiskWriteMbps`) +
            FfiConverterDouble.allocationSize(value.`receiverDiskWriteAvgUs`) +
            FfiConverterDouble.allocationSize(value.`receiverDiskWriteP95Us`) +
            FfiConverterUInt.allocationSize(value.`receiverMaxQueueDepth`) +
            FfiConverterULong.allocationSize(value.`receiverFinalizeMs`) +
            FfiConverterSequenceTypeFfiChannelMetric.allocationSize(value.`channels`) +
            FfiConverterString.allocationSize(value.`primaryBottleneck`) +
            FfiConverterSequenceString.allocationSize(value.`recommendations`)
    )

    override fun write(value: FfiBottleneckReport, buf: ByteBuffer) {
            FfiConverterString.write(value.`transferId`, buf)
            FfiConverterString.write(value.`fileName`, buf)
            FfiConverterULong.write(value.`fileSize`, buf)
            FfiConverterString.write(value.`role`, buf)
            FfiConverterULong.write(value.`totalDurationMs`, buf)
            FfiConverterDouble.write(value.`avgThroughputMbps`, buf)
            FfiConverterDouble.write(value.`peakThroughputMbps`, buf)
            FfiConverterDouble.write(value.`senderDiskReadMbps`, buf)
            FfiConverterDouble.write(value.`senderDiskReadAvgUs`, buf)
            FfiConverterDouble.write(value.`senderDiskReadP95Us`, buf)
            FfiConverterDouble.write(value.`senderChecksumMbps`, buf)
            FfiConverterDouble.write(value.`senderChecksumAvgUs`, buf)
            FfiConverterDouble.write(value.`receiverDiskWriteMbps`, buf)
            FfiConverterDouble.write(value.`receiverDiskWriteAvgUs`, buf)
            FfiConverterDouble.write(value.`receiverDiskWriteP95Us`, buf)
            FfiConverterUInt.write(value.`receiverMaxQueueDepth`, buf)
            FfiConverterULong.write(value.`receiverFinalizeMs`, buf)
            FfiConverterSequenceTypeFfiChannelMetric.write(value.`channels`, buf)
            FfiConverterString.write(value.`primaryBottleneck`, buf)
            FfiConverterSequenceString.write(value.`recommendations`, buf)
    }
}



data class FfiChannelMetric (
    var `channelName`: kotlin.String, 
    var `bytesTransferred`: kotlin.ULong, 
    var `chunksTransferred`: kotlin.UInt, 
    var `avgSocketWriteUs`: kotlin.Double, 
    var `avgRttMs`: kotlin.Double, 
    var `p95RttMs`: kotlin.Double, 
    var `nackCount`: kotlin.ULong, 
    var `disconnectCount`: kotlin.ULong
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiChannelMetric: FfiConverterRustBuffer<FfiChannelMetric> {
    override fun read(buf: ByteBuffer): FfiChannelMetric {
        return FfiChannelMetric(
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: FfiChannelMetric) = (
            FfiConverterString.allocationSize(value.`channelName`) +
            FfiConverterULong.allocationSize(value.`bytesTransferred`) +
            FfiConverterUInt.allocationSize(value.`chunksTransferred`) +
            FfiConverterDouble.allocationSize(value.`avgSocketWriteUs`) +
            FfiConverterDouble.allocationSize(value.`avgRttMs`) +
            FfiConverterDouble.allocationSize(value.`p95RttMs`) +
            FfiConverterULong.allocationSize(value.`nackCount`) +
            FfiConverterULong.allocationSize(value.`disconnectCount`)
    )

    override fun write(value: FfiChannelMetric, buf: ByteBuffer) {
            FfiConverterString.write(value.`channelName`, buf)
            FfiConverterULong.write(value.`bytesTransferred`, buf)
            FfiConverterUInt.write(value.`chunksTransferred`, buf)
            FfiConverterDouble.write(value.`avgSocketWriteUs`, buf)
            FfiConverterDouble.write(value.`avgRttMs`, buf)
            FfiConverterDouble.write(value.`p95RttMs`, buf)
            FfiConverterULong.write(value.`nackCount`, buf)
            FfiConverterULong.write(value.`disconnectCount`, buf)
    }
}



data class FfiDeviceInfo (
    var `deviceId`: kotlin.String, 
    var `deviceName`: kotlin.String, 
    var `transport`: kotlin.String, 
    var `isConnected`: kotlin.Boolean
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiDeviceInfo: FfiConverterRustBuffer<FfiDeviceInfo> {
    override fun read(buf: ByteBuffer): FfiDeviceInfo {
        return FfiDeviceInfo(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterBoolean.read(buf),
        )
    }

    override fun allocationSize(value: FfiDeviceInfo) = (
            FfiConverterString.allocationSize(value.`deviceId`) +
            FfiConverterString.allocationSize(value.`deviceName`) +
            FfiConverterString.allocationSize(value.`transport`) +
            FfiConverterBoolean.allocationSize(value.`isConnected`)
    )

    override fun write(value: FfiDeviceInfo, buf: ByteBuffer) {
            FfiConverterString.write(value.`deviceId`, buf)
            FfiConverterString.write(value.`deviceName`, buf)
            FfiConverterString.write(value.`transport`, buf)
            FfiConverterBoolean.write(value.`isConnected`, buf)
    }
}



data class FfiTransferEvent (
    var `timestampUs`: kotlin.ULong, 
    var `relativeMs`: kotlin.ULong, 
    var `stage`: kotlin.String, 
    var `level`: kotlin.String, 
    var `channel`: kotlin.String, 
    var `chunkId`: kotlin.UInt?, 
    var `durationUs`: kotlin.ULong?, 
    var `bytes`: kotlin.ULong?, 
    var `message`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiTransferEvent: FfiConverterRustBuffer<FfiTransferEvent> {
    override fun read(buf: ByteBuffer): FfiTransferEvent {
        return FfiTransferEvent(
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalUInt.read(buf),
            FfiConverterOptionalULong.read(buf),
            FfiConverterOptionalULong.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: FfiTransferEvent) = (
            FfiConverterULong.allocationSize(value.`timestampUs`) +
            FfiConverterULong.allocationSize(value.`relativeMs`) +
            FfiConverterString.allocationSize(value.`stage`) +
            FfiConverterString.allocationSize(value.`level`) +
            FfiConverterString.allocationSize(value.`channel`) +
            FfiConverterOptionalUInt.allocationSize(value.`chunkId`) +
            FfiConverterOptionalULong.allocationSize(value.`durationUs`) +
            FfiConverterOptionalULong.allocationSize(value.`bytes`) +
            FfiConverterString.allocationSize(value.`message`)
    )

    override fun write(value: FfiTransferEvent, buf: ByteBuffer) {
            FfiConverterULong.write(value.`timestampUs`, buf)
            FfiConverterULong.write(value.`relativeMs`, buf)
            FfiConverterString.write(value.`stage`, buf)
            FfiConverterString.write(value.`level`, buf)
            FfiConverterString.write(value.`channel`, buf)
            FfiConverterOptionalUInt.write(value.`chunkId`, buf)
            FfiConverterOptionalULong.write(value.`durationUs`, buf)
            FfiConverterOptionalULong.write(value.`bytes`, buf)
            FfiConverterString.write(value.`message`, buf)
    }
}



data class FfiTransferHandle (
    var `transferId`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiTransferHandle: FfiConverterRustBuffer<FfiTransferHandle> {
    override fun read(buf: ByteBuffer): FfiTransferHandle {
        return FfiTransferHandle(
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: FfiTransferHandle) = (
            FfiConverterString.allocationSize(value.`transferId`)
    )

    override fun write(value: FfiTransferHandle, buf: ByteBuffer) {
            FfiConverterString.write(value.`transferId`, buf)
    }
}



data class FfiTransferLogSummary (
    var `transferId`: kotlin.String, 
    var `fileName`: kotlin.String, 
    var `fileSize`: kotlin.ULong, 
    var `role`: kotlin.String, 
    var `avgThroughputMbps`: kotlin.Double, 
    var `primaryBottleneck`: kotlin.String, 
    var `logFilePath`: kotlin.String, 
    var `jsonFilePath`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiTransferLogSummary: FfiConverterRustBuffer<FfiTransferLogSummary> {
    override fun read(buf: ByteBuffer): FfiTransferLogSummary {
        return FfiTransferLogSummary(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: FfiTransferLogSummary) = (
            FfiConverterString.allocationSize(value.`transferId`) +
            FfiConverterString.allocationSize(value.`fileName`) +
            FfiConverterULong.allocationSize(value.`fileSize`) +
            FfiConverterString.allocationSize(value.`role`) +
            FfiConverterDouble.allocationSize(value.`avgThroughputMbps`) +
            FfiConverterString.allocationSize(value.`primaryBottleneck`) +
            FfiConverterString.allocationSize(value.`logFilePath`) +
            FfiConverterString.allocationSize(value.`jsonFilePath`)
    )

    override fun write(value: FfiTransferLogSummary, buf: ByteBuffer) {
            FfiConverterString.write(value.`transferId`, buf)
            FfiConverterString.write(value.`fileName`, buf)
            FfiConverterULong.write(value.`fileSize`, buf)
            FfiConverterString.write(value.`role`, buf)
            FfiConverterDouble.write(value.`avgThroughputMbps`, buf)
            FfiConverterString.write(value.`primaryBottleneck`, buf)
            FfiConverterString.write(value.`logFilePath`, buf)
            FfiConverterString.write(value.`jsonFilePath`, buf)
    }
}



data class FfiTransferProgress (
    var `transferId`: kotlin.String, 
    var `fileName`: kotlin.String, 
    var `fileSize`: kotlin.ULong, 
    var `bytesTransferred`: kotlin.ULong, 
    var `percent`: kotlin.Double, 
    var `usbThroughputBps`: kotlin.Double, 
    var `wifiThroughputBps`: kotlin.Double, 
    var `aggregateThroughputBps`: kotlin.Double, 
    var `etaSeconds`: kotlin.ULong?, 
    var `totalChunks`: kotlin.UInt, 
    var `completedChunks`: kotlin.UInt, 
    var `retryCount`: kotlin.ULong, 
    var `usbErrors`: kotlin.ULong, 
    var `wifiErrors`: kotlin.ULong, 
    var `status`: FfiTransferStatus
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiTransferProgress: FfiConverterRustBuffer<FfiTransferProgress> {
    override fun read(buf: ByteBuffer): FfiTransferProgress {
        return FfiTransferProgress(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterDouble.read(buf),
            FfiConverterOptionalULong.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterTypeFfiTransferStatus.read(buf),
        )
    }

    override fun allocationSize(value: FfiTransferProgress) = (
            FfiConverterString.allocationSize(value.`transferId`) +
            FfiConverterString.allocationSize(value.`fileName`) +
            FfiConverterULong.allocationSize(value.`fileSize`) +
            FfiConverterULong.allocationSize(value.`bytesTransferred`) +
            FfiConverterDouble.allocationSize(value.`percent`) +
            FfiConverterDouble.allocationSize(value.`usbThroughputBps`) +
            FfiConverterDouble.allocationSize(value.`wifiThroughputBps`) +
            FfiConverterDouble.allocationSize(value.`aggregateThroughputBps`) +
            FfiConverterOptionalULong.allocationSize(value.`etaSeconds`) +
            FfiConverterUInt.allocationSize(value.`totalChunks`) +
            FfiConverterUInt.allocationSize(value.`completedChunks`) +
            FfiConverterULong.allocationSize(value.`retryCount`) +
            FfiConverterULong.allocationSize(value.`usbErrors`) +
            FfiConverterULong.allocationSize(value.`wifiErrors`) +
            FfiConverterTypeFfiTransferStatus.allocationSize(value.`status`)
    )

    override fun write(value: FfiTransferProgress, buf: ByteBuffer) {
            FfiConverterString.write(value.`transferId`, buf)
            FfiConverterString.write(value.`fileName`, buf)
            FfiConverterULong.write(value.`fileSize`, buf)
            FfiConverterULong.write(value.`bytesTransferred`, buf)
            FfiConverterDouble.write(value.`percent`, buf)
            FfiConverterDouble.write(value.`usbThroughputBps`, buf)
            FfiConverterDouble.write(value.`wifiThroughputBps`, buf)
            FfiConverterDouble.write(value.`aggregateThroughputBps`, buf)
            FfiConverterOptionalULong.write(value.`etaSeconds`, buf)
            FfiConverterUInt.write(value.`totalChunks`, buf)
            FfiConverterUInt.write(value.`completedChunks`, buf)
            FfiConverterULong.write(value.`retryCount`, buf)
            FfiConverterULong.write(value.`usbErrors`, buf)
            FfiConverterULong.write(value.`wifiErrors`, buf)
            FfiConverterTypeFfiTransferStatus.write(value.`status`, buf)
    }
}



data class FfiTransferSummary (
    var `transferId`: kotlin.String, 
    var `fileName`: kotlin.String, 
    var `fileSize`: kotlin.ULong, 
    var `status`: FfiTransferStatus, 
    var `role`: FfiTransferRole
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiTransferSummary: FfiConverterRustBuffer<FfiTransferSummary> {
    override fun read(buf: ByteBuffer): FfiTransferSummary {
        return FfiTransferSummary(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterTypeFfiTransferStatus.read(buf),
            FfiConverterTypeFfiTransferRole.read(buf),
        )
    }

    override fun allocationSize(value: FfiTransferSummary) = (
            FfiConverterString.allocationSize(value.`transferId`) +
            FfiConverterString.allocationSize(value.`fileName`) +
            FfiConverterULong.allocationSize(value.`fileSize`) +
            FfiConverterTypeFfiTransferStatus.allocationSize(value.`status`) +
            FfiConverterTypeFfiTransferRole.allocationSize(value.`role`)
    )

    override fun write(value: FfiTransferSummary, buf: ByteBuffer) {
            FfiConverterString.write(value.`transferId`, buf)
            FfiConverterString.write(value.`fileName`, buf)
            FfiConverterULong.write(value.`fileSize`, buf)
            FfiConverterTypeFfiTransferStatus.write(value.`status`, buf)
            FfiConverterTypeFfiTransferRole.write(value.`role`, buf)
    }
}



data class FfiWifiHotspotInfo (
    var `ssid`: kotlin.String, 
    var `passphrase`: kotlin.String, 
    var `ip`: kotlin.String, 
    var `port`: kotlin.UShort, 
    var `band`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiWifiHotspotInfo: FfiConverterRustBuffer<FfiWifiHotspotInfo> {
    override fun read(buf: ByteBuffer): FfiWifiHotspotInfo {
        return FfiWifiHotspotInfo(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterUShort.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: FfiWifiHotspotInfo) = (
            FfiConverterString.allocationSize(value.`ssid`) +
            FfiConverterString.allocationSize(value.`passphrase`) +
            FfiConverterString.allocationSize(value.`ip`) +
            FfiConverterUShort.allocationSize(value.`port`) +
            FfiConverterString.allocationSize(value.`band`)
    )

    override fun write(value: FfiWifiHotspotInfo, buf: ByteBuffer) {
            FfiConverterString.write(value.`ssid`, buf)
            FfiConverterString.write(value.`passphrase`, buf)
            FfiConverterString.write(value.`ip`, buf)
            FfiConverterUShort.write(value.`port`, buf)
            FfiConverterString.write(value.`band`, buf)
    }
}





sealed class FfiTransferException: kotlin.Exception() {
    
    class Generic(
        
        val `msg`: kotlin.String
        ) : FfiTransferException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<FfiTransferException> {
        override fun lift(error_buf: RustBuffer.ByValue): FfiTransferException = FfiConverterTypeFfiTransferError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiTransferError : FfiConverterRustBuffer<FfiTransferException> {
    override fun read(buf: ByteBuffer): FfiTransferException {
        

        return when(buf.getInt()) {
            1 -> FfiTransferException.Generic(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: FfiTransferException): ULong {
        return when(value) {
            is FfiTransferException.Generic -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
        }
    }

    override fun write(value: FfiTransferException, buf: ByteBuffer) {
        when(value) {
            is FfiTransferException.Generic -> {
                buf.putInt(1)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




enum class FfiTransferRole {
    
    SENDER,
    RECEIVER;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeFfiTransferRole: FfiConverterRustBuffer<FfiTransferRole> {
    override fun read(buf: ByteBuffer) = try {
        FfiTransferRole.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: FfiTransferRole) = 4UL

    override fun write(value: FfiTransferRole, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class FfiTransferStatus {
    
    IN_PROGRESS,
    COMPLETED,
    PAUSED,
    FAILED,
    CANCELLED;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeFfiTransferStatus: FfiConverterRustBuffer<FfiTransferStatus> {
    override fun read(buf: ByteBuffer) = try {
        FfiTransferStatus.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: FfiTransferStatus) = 4UL

    override fun write(value: FfiTransferStatus, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class FfiTransportPreference {
    
    AUTOMATIC,
    COMBINED,
    USB_ONLY,
    WIFI_DIRECT_ONLY;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeFfiTransportPreference: FfiConverterRustBuffer<FfiTransportPreference> {
    override fun read(buf: ByteBuffer) = try {
        FfiTransportPreference.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: FfiTransportPreference) = 4UL

    override fun write(value: FfiTransportPreference, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






/**
 * @suppress
 */
public object FfiConverterOptionalUInt: FfiConverterRustBuffer<kotlin.UInt?> {
    override fun read(buf: ByteBuffer): kotlin.UInt? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterUInt.read(buf)
    }

    override fun allocationSize(value: kotlin.UInt?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterUInt.allocationSize(value)
        }
    }

    override fun write(value: kotlin.UInt?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterUInt.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalULong: FfiConverterRustBuffer<kotlin.ULong?> {
    override fun read(buf: ByteBuffer): kotlin.ULong? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterULong.read(buf)
    }

    override fun allocationSize(value: kotlin.ULong?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterULong.allocationSize(value)
        }
    }

    override fun write(value: kotlin.ULong?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterULong.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeFfiBottleneckReport: FfiConverterRustBuffer<FfiBottleneckReport?> {
    override fun read(buf: ByteBuffer): FfiBottleneckReport? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeFfiBottleneckReport.read(buf)
    }

    override fun allocationSize(value: FfiBottleneckReport?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeFfiBottleneckReport.allocationSize(value)
        }
    }

    override fun write(value: FfiBottleneckReport?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeFfiBottleneckReport.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeFfiTransferProgress: FfiConverterRustBuffer<FfiTransferProgress?> {
    override fun read(buf: ByteBuffer): FfiTransferProgress? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeFfiTransferProgress.read(buf)
    }

    override fun allocationSize(value: FfiTransferProgress?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeFfiTransferProgress.allocationSize(value)
        }
    }

    override fun write(value: FfiTransferProgress?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeFfiTransferProgress.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceString: FfiConverterRustBuffer<List<kotlin.String>> {
    override fun read(buf: ByteBuffer): List<kotlin.String> {
        val len = buf.getInt()
        return List<kotlin.String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.String>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiChannelMetric: FfiConverterRustBuffer<List<FfiChannelMetric>> {
    override fun read(buf: ByteBuffer): List<FfiChannelMetric> {
        val len = buf.getInt()
        return List<FfiChannelMetric>(len) {
            FfiConverterTypeFfiChannelMetric.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiChannelMetric>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiChannelMetric.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiChannelMetric>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiChannelMetric.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiDeviceInfo: FfiConverterRustBuffer<List<FfiDeviceInfo>> {
    override fun read(buf: ByteBuffer): List<FfiDeviceInfo> {
        val len = buf.getInt()
        return List<FfiDeviceInfo>(len) {
            FfiConverterTypeFfiDeviceInfo.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiDeviceInfo>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiDeviceInfo.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiDeviceInfo>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiDeviceInfo.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiTransferEvent: FfiConverterRustBuffer<List<FfiTransferEvent>> {
    override fun read(buf: ByteBuffer): List<FfiTransferEvent> {
        val len = buf.getInt()
        return List<FfiTransferEvent>(len) {
            FfiConverterTypeFfiTransferEvent.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiTransferEvent>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiTransferEvent.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiTransferEvent>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiTransferEvent.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiTransferLogSummary: FfiConverterRustBuffer<List<FfiTransferLogSummary>> {
    override fun read(buf: ByteBuffer): List<FfiTransferLogSummary> {
        val len = buf.getInt()
        return List<FfiTransferLogSummary>(len) {
            FfiConverterTypeFfiTransferLogSummary.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiTransferLogSummary>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiTransferLogSummary.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiTransferLogSummary>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiTransferLogSummary.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiTransferSummary: FfiConverterRustBuffer<List<FfiTransferSummary>> {
    override fun read(buf: ByteBuffer): List<FfiTransferSummary> {
        val len = buf.getInt()
        return List<FfiTransferSummary>(len) {
            FfiConverterTypeFfiTransferSummary.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiTransferSummary>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiTransferSummary.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiTransferSummary>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiTransferSummary.write(it, buf)
        }
    }
} fun `cancelTransfer`(`transferId`: kotlin.String)
        = 
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_turbotransfer_core_fn_func_cancel_transfer(
        FfiConverterString.lower(`transferId`),_status)
}
    
    

    @Throws(FfiTransferException::class) fun `enterReceiveMode`(`address`: kotlin.String?, `destDir`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(FfiTransferException) { _status ->
    UniffiLib.INSTANCE.uniffi_turbotransfer_core_fn_func_enter_receive_mode(
        FfiConverterOptionalString.lower(`address`),FfiConverterString.lower(`destDir`),_status)
}
    )
    }
    

    @Throws(FfiTransferException::class) fun `exportTransferLogs`(`transferId`: kotlin.String, `outputDir`: kotlin.String?): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(FfiTransferException) { _status ->
    UniffiLib.INSTANCE.uniffi_turbotransfer_core_fn_func_export_transfer_logs(
        FfiConverterString.lower(`transferId`),FfiConverterOptionalString.lower(`outputDir`),_status)
}
    )
    }
    
 fun `getDevices`(): List<FfiDeviceInfo> {
            return FfiConverterSequenceTypeFfiDeviceInfo.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_turbotransfer_core_fn_func_get_devices(
        _status)
}
    )
    }
    
 fun `getProgress`(`transferId`: kotlin.String): FfiTransferProgress? {
            return FfiConverterOptionalTypeFfiTransferProgress.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_turbotransfer_core_fn_func_get_progress(
        FfiConverterString.lower(`transferId`),_status)
}
    )
    }
    
 fun `getTransferBottleneckReport`(`transferId`: kotlin.String): FfiBottleneckReport? {
            return FfiConverterOptionalTypeFfiBottleneckReport.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_turbotransfer_core_fn_func_get_transfer_bottleneck_report(
        FfiConverterString.lower(`transferId`),_status)
}
    )
    }
    
 fun `getTransferLogJson`(`transferId`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_turbotransfer_core_fn_func_get_transfer_log_json(
        FfiConverterString.lower(`transferId`),_status)
}
    )
    }
    
 fun `getTransferLogs`(`transferId`: kotlin.String, `maxEvents`: kotlin.UInt?): List<FfiTransferEvent> {
            return FfiConverterSequenceTypeFfiTransferEvent.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_turbotransfer_core_fn_func_get_transfer_logs(
        FfiConverterString.lower(`transferId`),FfiConverterOptionalUInt.lower(`maxEvents`),_status)
}
    )
    }
    
 fun `getTransfers`(): List<FfiTransferSummary> {
            return FfiConverterSequenceTypeFfiTransferSummary.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_turbotransfer_core_fn_func_get_transfers(
        _status)
}
    )
    }
    
 fun `initLogger`()
        = 
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_turbotransfer_core_fn_func_init_logger(
        _status)
}
    
    
 fun `listTransferLogs`(): List<FfiTransferLogSummary> {
            return FfiConverterSequenceTypeFfiTransferLogSummary.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_turbotransfer_core_fn_func_list_transfer_logs(
        _status)
}
    )
    }
    
 fun `pauseTransfer`(`transferId`: kotlin.String)
        = 
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_turbotransfer_core_fn_func_pause_transfer(
        FfiConverterString.lower(`transferId`),_status)
}
    
    

    @Throws(FfiTransferException::class) fun `resumeTransfer`(`transferId`: kotlin.String, `transportPref`: FfiTransportPreference): FfiTransferHandle {
            return FfiConverterTypeFfiTransferHandle.lift(
    uniffiRustCallWithError(FfiTransferException) { _status ->
    UniffiLib.INSTANCE.uniffi_turbotransfer_core_fn_func_resume_transfer(
        FfiConverterString.lower(`transferId`),FfiConverterTypeFfiTransportPreference.lower(`transportPref`),_status)
}
    )
    }
    
 fun `setDataDirectory`(`path`: kotlin.String)
        = 
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_turbotransfer_core_fn_func_set_data_directory(
        FfiConverterString.lower(`path`),_status)
}
    
    

    @Throws(FfiTransferException::class) fun `startTransfer`(`filePath`: kotlin.String, `fileName`: kotlin.String?, `deviceId`: kotlin.String?, `transportPref`: FfiTransportPreference, `address`: kotlin.String?): FfiTransferHandle {
            return FfiConverterTypeFfiTransferHandle.lift(
    uniffiRustCallWithError(FfiTransferException) { _status ->
    UniffiLib.INSTANCE.uniffi_turbotransfer_core_fn_func_start_transfer(
        FfiConverterString.lower(`filePath`),FfiConverterOptionalString.lower(`fileName`),FfiConverterOptionalString.lower(`deviceId`),FfiConverterTypeFfiTransportPreference.lower(`transportPref`),FfiConverterOptionalString.lower(`address`),_status)
}
    )
    }
    
 fun `stopReceiveMode`(): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_turbotransfer_core_fn_func_stop_receive_mode(
        _status)
}
    )
    }
    


